#ifndef RUNLEVEL_H
#define RUNLEVEL_H

enum runLevel {
	RL_INIT,
	RL_SETUP,
	RL_TRACE_EXECUTE,
	RL_TRACE_EXECUTE_NO_DEBUGABLE,
	RL_TRACE_EXECUTE_IS_DEBUGABLE,
	RL_TRACE_EXECUTE_RUN,
	RL_DBG_RECORD_DRAWCALL,
	RL_DBG_VERTEX_SHADER,
	RL_DBG_GEOMETRY_SHADER,
	RL_DBG_FRAGMENT_SHADER,
	RL_DBG_RESTART,
	RL_DBG_LAST
};

static const char* const runlevel_names[RL_DBG_LAST] = {
	"RL_INIT", "RL_SETUP", "RL_TRACE_EXECUTE", "RL_TRACE_EXECUTE_NO_DEBUGABLE",
	"RL_TRACE_EXECUTE_IS_DEBUGABLE", "RL_TRACE_EXECUTE_RUN", "RL_DBG_RECORD_DRAWCALL",
	"RL_DBG_VERTEX_SHADER", "RL_DBG_GEOMETRY_SHADER", "RL_DBG_FRAGMENT_SHADER",
	"RL_DBG_RESTART",
};

#endif /* RUNLEVEL_H */
