/******************************************************************************

Copyright (C) 2006-2009 Institute for Visualization and Interactive Systems
(VIS), Universität Stuttgart.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

  * Redistributions of source code must retain the above copyright notice, this
	list of conditions and the following disclaimer.

  * Redistributions in binary form must reproduce the above copyright notice, this
	list of conditions and the following disclaimer in the documentation and/or
	other materials provided with the distribution.

  * Neither the name of the name of VIS, Universität Stuttgart nor the names
	of its contributors may be used to endorse or promote products derived from
	this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*******************************************************************************/

#ifndef _STREAMRECORDING_H
#define _STREAMRECORDING_H

#include "debuglibExport.h"


GLAPI void APIENTRY glVertexAttribI1i (GLuint, GLint);
GLAPI void APIENTRY glVertexAttribI2i (GLuint, GLint, GLint);
GLAPI void APIENTRY glVertexAttribI3i (GLuint, GLint, GLint, GLint);
GLAPI void APIENTRY glVertexAttribI4i (GLuint, GLint, GLint, GLint, GLint);
GLAPI void APIENTRY glVertexAttribI1ui (GLuint, GLuint);
GLAPI void APIENTRY glVertexAttribI2ui (GLuint, GLuint, GLuint);
GLAPI void APIENTRY glVertexAttribI3ui (GLuint, GLuint, GLuint, GLuint);
GLAPI void APIENTRY glVertexAttribI4ui (GLuint, GLuint, GLuint, GLuint, GLuint);
GLAPI void APIENTRY glVertexAttribI1iv (GLuint, const GLint *);
GLAPI void APIENTRY glVertexAttribI2iv (GLuint, const GLint *);
GLAPI void APIENTRY glVertexAttribI3iv (GLuint, const GLint *);
GLAPI void APIENTRY glVertexAttribI4iv (GLuint, const GLint *);
GLAPI void APIENTRY glVertexAttribI1uiv (GLuint, const GLuint *);
GLAPI void APIENTRY glVertexAttribI2uiv (GLuint, const GLuint *);
GLAPI void APIENTRY glVertexAttribI3uiv (GLuint, const GLuint *);
GLAPI void APIENTRY glVertexAttribI4uiv (GLuint, const GLuint *);
GLAPI void APIENTRY glVertexAttribI4bv (GLuint, const GLbyte *);
GLAPI void APIENTRY glVertexAttribI4sv (GLuint, const GLshort *);
GLAPI void APIENTRY glVertexAttribI4ubv (GLuint, const GLubyte *);
GLAPI void APIENTRY glVertexAttribI4usv (GLuint, const GLushort *);

GLAPI void APIENTRY glDrawArraysInstanced (GLenum, GLint, GLsizei, GLsizei);
GLAPI void APIENTRY glPrimitiveRestartIndex (GLuint);


/* size function prototypes */
#if 0
DBGLIBLOCAL int glBitmap_getArg6Size(GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap);
DBGLIBLOCAL int glCallLists_getArg2Size(GLsizei n, GLenum type, const GLvoid *lists);
DBGLIBLOCAL int glClipPlane_getArg1Size(GLenum plane, const GLdouble *equation);
DBGLIBLOCAL int glColorPointer_getArg3Size(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
DBGLIBLOCAL int glDeleteTextures_getArg1Size(GLsizei n, const GLuint *textures);
DBGLIBLOCAL int glDrawElements_getArg3Size(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices);
DBGLIBLOCAL int glDrawPixels_getArg4Size(GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
DBGLIBLOCAL int glEdgeFlagPointer_getArg1Size(GLsizei stride, const GLvoid *pointer);
DBGLIBLOCAL int glEdgeFlagv_getArg0Size(const GLboolean *flag);
DBGLIBLOCAL int glFeedbackBuffer_getArg2Size(GLsizei size, GLenum type, GLfloat *buffer);
DBGLIBLOCAL int glFogfv_getArg1Size(GLenum pname, const GLfloat *params);
DBGLIBLOCAL int glFogiv_getArg1Size(GLenum pname, const GLint *params);
DBGLIBLOCAL int glIndexPointer_getArg2Size(GLenum type, GLsizei stride, const GLvoid *pointer);
DBGLIBLOCAL int glIndexdv_getArg0Size(const GLdouble *c);
DBGLIBLOCAL int glIndexfv_getArg0Size(const GLfloat *c);
DBGLIBLOCAL int glIndexiv_getArg0Size(const GLint *c);
DBGLIBLOCAL int glIndexsv_getArg0Size(const GLshort *c);
DBGLIBLOCAL int glIndexubv_getArg0Size(const GLubyte *c);
DBGLIBLOCAL int glInterleavedArrays_getArg2Size(GLenum format, GLsizei stride, const GLvoid *pointer);
DBGLIBLOCAL int glLightModelfv_getArg1Size(GLenum pname, const GLfloat *params);
DBGLIBLOCAL int glLightModeliv_getArg1Size(GLenum pname, const GLint *params);
DBGLIBLOCAL int glLightfv_getArg2Size(GLenum light, GLenum pname, const GLfloat *params);
DBGLIBLOCAL int glLightiv_getArg2Size(GLenum light, GLenum pname, const GLint *params);
DBGLIBLOCAL int glLoadMatrixd_getArg0Size(const GLdouble *m);
DBGLIBLOCAL int glLoadMatrixf_getArg0Size(const GLfloat *m);
DBGLIBLOCAL int glMap1d_getArg5Size(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points);
DBGLIBLOCAL int glMap1f_getArg5Size(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points);
DBGLIBLOCAL int glMap2d_getArg9Size(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points);
DBGLIBLOCAL int glMap2f_getArg9Size(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points);
DBGLIBLOCAL int glMaterialfv_getArg2Size(GLenum face, GLenum pname, const GLfloat *params);
DBGLIBLOCAL int glMaterialiv_getArg2Size(GLenum face, GLenum pname, const GLint *params);
DBGLIBLOCAL int glMultMatrixd_getArg0Size(const GLdouble *m);
DBGLIBLOCAL int glMultMatrixf_getArg0Size(const GLfloat *m);
DBGLIBLOCAL int glNormalPointer_getArg2Size(GLenum type, GLsizei stride, const GLvoid *pointer);
DBGLIBLOCAL int glPixelMapfv_getArg2Size(GLenum map, GLsizei mapsize, const GLfloat *values);
DBGLIBLOCAL int glPixelMapuiv_getArg2Size(GLenum map, GLsizei mapsize, const GLuint *values);
DBGLIBLOCAL int glPixelMapusv_getArg2Size(GLenum map, GLsizei mapsize, const GLushort *values);
DBGLIBLOCAL int glPolygonStipple_getArg0Size(const GLubyte *mask);
DBGLIBLOCAL int glPrioritizeTextures_getArg1Size(GLsizei n, const GLuint *textures, const GLclampf *priorities);
DBGLIBLOCAL int glPrioritizeTextures_getArg2Size(GLsizei n, const GLuint *textures, const GLclampf *priorities);
DBGLIBLOCAL int glReadPixels_getArg6Size(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels);
DBGLIBLOCAL int glRectdv_getArg0Size(const GLdouble *v1, const GLdouble *v2);
DBGLIBLOCAL int glRectdv_getArg1Size(const GLdouble *v1, const GLdouble *v2);
DBGLIBLOCAL int glRectfv_getArg0Size(const GLfloat *v1, const GLfloat *v2);
DBGLIBLOCAL int glRectfv_getArg1Size(const GLfloat *v1, const GLfloat *v2);
DBGLIBLOCAL int glRectiv_getArg0Size(const GLint *v1, const GLint *v2);
DBGLIBLOCAL int glRectiv_getArg1Size(const GLint *v1, const GLint *v2);
DBGLIBLOCAL int glRectsv_getArg0Size(const GLshort *v1, const GLshort *v2);
DBGLIBLOCAL int glRectsv_getArg1Size(const GLshort *v1, const GLshort *v2);
DBGLIBLOCAL int glSelectBuffer_getArg1Size(GLsizei size, GLuint *buffer);
DBGLIBLOCAL int glTexCoordPointer_getArg3Size(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
DBGLIBLOCAL int glTexEnvfv_getArg2Size(GLenum target, GLenum pname, const GLfloat *params);
DBGLIBLOCAL int glTexEnviv_getArg2Size(GLenum target, GLenum pname, const GLint *params);
DBGLIBLOCAL int glTexGendv_getArg2Size(GLenum coord, GLenum pname, const GLdouble *params);
DBGLIBLOCAL int glTexGenfv_getArg2Size(GLenum coord, GLenum pname, const GLfloat *params);
DBGLIBLOCAL int glTexGeniv_getArg2Size(GLenum coord, GLenum pname, const GLint *params);
DBGLIBLOCAL int glTexImage1D_getArg7Size(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
DBGLIBLOCAL int glTexImage2D_getArg8Size(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
DBGLIBLOCAL int glTexParameterfv_getArg2Size(GLenum target, GLenum pname, const GLfloat *params);
DBGLIBLOCAL int glTexParameteriv_getArg2Size(GLenum target, GLenum pname, const GLint *params);
DBGLIBLOCAL int glTexSubImage1D_getArg6Size(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels);
DBGLIBLOCAL int glTexSubImage2D_getArg8Size(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
DBGLIBLOCAL int glVertexPointer_getArg3Size(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
DBGLIBLOCAL int glDrawRangeElements_getArg5Size(GLenum, GLuint, GLuint, GLsizei, GLenum, const GLvoid *);
DBGLIBLOCAL int glColorTable_getArg5Size(GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *);
DBGLIBLOCAL int glColorTableParameterfv_getArg2Size(GLenum, GLenum, const GLfloat *);
DBGLIBLOCAL int glColorTableParameteriv_getArg2Size(GLenum, GLenum, const GLint *);
DBGLIBLOCAL int glColorSubTable_getArg5Size(GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
DBGLIBLOCAL int glConvolutionFilter1D_getArg5Size(GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *);
DBGLIBLOCAL int glConvolutionFilter2D_getArg6Size(GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
DBGLIBLOCAL int glConvolutionParameterfv_getArg2Size(GLenum, GLenum, const GLfloat *);
DBGLIBLOCAL int glConvolutionParameteriv_getArg2Size(GLenum, GLenum, const GLint *);
DBGLIBLOCAL int glSeparableFilter2D_getArg6Size(GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *, const GLvoid *);
DBGLIBLOCAL int glSeparableFilter2D_getArg7Size(GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *, const GLvoid *);
DBGLIBLOCAL int glTexImage3D_getArg9Size(GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
DBGLIBLOCAL int glTexSubImage3D_getArg10Size(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
DBGLIBLOCAL int glLoadTransposeMatrixf_getArg0Size(const GLfloat *);
DBGLIBLOCAL int glLoadTransposeMatrixd_getArg0Size(const GLdouble *);
DBGLIBLOCAL int glMultTransposeMatrixf_getArg0Size(const GLfloat *);
DBGLIBLOCAL int glMultTransposeMatrixd_getArg0Size(const GLdouble *);
DBGLIBLOCAL int glCompressedTexImage3D_getArg8Size(GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *);
DBGLIBLOCAL int glCompressedTexImage2D_getArg7Size(GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *);
DBGLIBLOCAL int glCompressedTexImage1D_getArg6Size(GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, const GLvoid *);
DBGLIBLOCAL int glCompressedTexSubImage3D_getArg10Size(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *);
DBGLIBLOCAL int glCompressedTexSubImage2D_getArg8Size(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *);
DBGLIBLOCAL int glCompressedTexSubImage1D_getArg6Size(GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, const GLvoid *);
DBGLIBLOCAL int glFogCoordfv_getArg0Size(const GLfloat *);
DBGLIBLOCAL int glFogCoorddv_getArg0Size(const GLdouble *);
DBGLIBLOCAL int glFogCoordPointer_getArg2Size(GLenum, GLsizei, const GLvoid *);
DBGLIBLOCAL int glMultiDrawArrays_getArg1Size(GLenum, GLint *, GLsizei *, GLsizei);
DBGLIBLOCAL int glMultiDrawArrays_getArg2Size(GLenum, GLint *, GLsizei *, GLsizei);
DBGLIBLOCAL int glMultiDrawElements_getArg1Size(GLenum, const GLsizei *, GLenum, const GLvoid* *, GLsizei);
DBGLIBLOCAL int glMultiDrawElements_getArg3Size(GLenum, const GLsizei *, GLenum, const GLvoid* *, GLsizei);
DBGLIBLOCAL int glPointParameterfv_getArg1Size(GLenum, const GLfloat *);
DBGLIBLOCAL int glPointParameteriv_getArg1Size(GLenum, const GLint *);
DBGLIBLOCAL int glSecondaryColorPointer_getArg3Size(GLint, GLenum, GLsizei, const GLvoid *);
DBGLIBLOCAL int glDeleteQueries_getArg1Size(GLsizei, const GLuint *);
DBGLIBLOCAL int glDeleteBuffers_getArg1Size(GLsizei, const GLuint *);
DBGLIBLOCAL int glBufferData_getArg2Size(GLenum, GLsizeiptr, const GLvoid *, GLenum);
DBGLIBLOCAL int glBufferSubData_getArg3Size(GLenum, GLintptr, GLsizeiptr, const GLvoid *);
DBGLIBLOCAL int glDrawBuffers_getArg1Size(GLsizei, const GLenum *);
DBGLIBLOCAL int glBindAttribLocation_getArg2Size(GLuint, GLuint, const GLchar *);
DBGLIBLOCAL int glShaderSource_getArg2Size(GLuint, GLsizei, const GLchar* *, const GLint *);
DBGLIBLOCAL int glShaderSource_getArg3Size(GLuint, GLsizei, const GLchar* *, const GLint *);
DBGLIBLOCAL int glVertexAttrib4Nubv_getArg1Size(GLuint, const GLubyte *);
DBGLIBLOCAL int glVertexAttrib4Nuiv_getArg1Size(GLuint, const GLuint *);
DBGLIBLOCAL int glVertexAttrib4Nusv_getArg1Size(GLuint, const GLushort *);
DBGLIBLOCAL int glVertexAttribPointer_getArg5Size(GLuint, GLint, GLenum, GLboolean, GLsizei, const GLvoid *);
DBGLIBLOCAL int glUniformMatrix2x3fv_getArg3Size(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
DBGLIBLOCAL int glUniformMatrix3x2fv_getArg3Size(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
DBGLIBLOCAL int glUniformMatrix2x4fv_getArg3Size(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
DBGLIBLOCAL int glUniformMatrix4x2fv_getArg3Size(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
DBGLIBLOCAL int glUniformMatrix3x4fv_getArg3Size(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
DBGLIBLOCAL int glUniformMatrix4x3fv_getArg3Size(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
DBGLIBLOCAL int glLoadTransposeMatrixfARB_getArg0Size(const GLfloat *);
DBGLIBLOCAL int glLoadTransposeMatrixdARB_getArg0Size(const GLdouble *);
DBGLIBLOCAL int glMultTransposeMatrixfARB_getArg0Size(const GLfloat *);
DBGLIBLOCAL int glMultTransposeMatrixdARB_getArg0Size(const GLdouble *);
DBGLIBLOCAL int glCompressedTexImage3DARB_getArg8Size(GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *);
DBGLIBLOCAL int glCompressedTexImage2DARB_getArg7Size(GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *);
DBGLIBLOCAL int glCompressedTexImage1DARB_getArg6Size(GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, const GLvoid *);
DBGLIBLOCAL int glCompressedTexSubImage3DARB_getArg10Size(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *);
DBGLIBLOCAL int glCompressedTexSubImage2DARB_getArg8Size(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *);
DBGLIBLOCAL int glCompressedTexSubImage1DARB_getArg6Size(GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, const GLvoid *);
DBGLIBLOCAL int glPointParameterfvARB_getArg1Size(GLenum, const GLfloat *);
DBGLIBLOCAL int glWeightbvARB_getArg1Size(GLint, const GLbyte *);
DBGLIBLOCAL int glWeightsvARB_getArg1Size(GLint, const GLshort *);
DBGLIBLOCAL int glWeightivARB_getArg1Size(GLint, const GLint *);
DBGLIBLOCAL int glWeightfvARB_getArg1Size(GLint, const GLfloat *);
DBGLIBLOCAL int glWeightdvARB_getArg1Size(GLint, const GLdouble *);
DBGLIBLOCAL int glWeightubvARB_getArg1Size(GLint, const GLubyte *);
DBGLIBLOCAL int glWeightusvARB_getArg1Size(GLint, const GLushort *);
DBGLIBLOCAL int glWeightuivARB_getArg1Size(GLint, const GLuint *);
DBGLIBLOCAL int glWeightPointerARB_getArg3Size(GLint, GLenum, GLsizei, const GLvoid *);
DBGLIBLOCAL int glMatrixIndexubvARB_getArg1Size(GLint, const GLubyte *);
DBGLIBLOCAL int glMatrixIndexusvARB_getArg1Size(GLint, const GLushort *);
DBGLIBLOCAL int glMatrixIndexuivARB_getArg1Size(GLint, const GLuint *);
DBGLIBLOCAL int glMatrixIndexPointerARB_getArg3Size(GLint, GLenum, GLsizei, const GLvoid *);
DBGLIBLOCAL int glVertexAttrib4NubvARB_getArg1Size(GLuint, const GLubyte *);
DBGLIBLOCAL int glVertexAttrib4NuivARB_getArg1Size(GLuint, const GLuint *);
DBGLIBLOCAL int glVertexAttrib4NusvARB_getArg1Size(GLuint, const GLushort *);
DBGLIBLOCAL int glVertexAttribPointerARB_getArg5Size(GLuint, GLint, GLenum, GLboolean, GLsizei, const GLvoid *);
DBGLIBLOCAL int glProgramStringARB_getArg3Size(GLenum, GLenum, GLsizei, const GLvoid *);
DBGLIBLOCAL int glDeleteProgramsARB_getArg1Size(GLsizei, const GLuint *);
DBGLIBLOCAL int glDeleteBuffersARB_getArg1Size(GLsizei, const GLuint *);
DBGLIBLOCAL int glBufferDataARB_getArg2Size(GLenum, GLsizeiptrARB, const GLvoid *, GLenum);
DBGLIBLOCAL int glBufferSubDataARB_getArg3Size(GLenum, GLintptrARB, GLsizeiptrARB, const GLvoid *);
DBGLIBLOCAL int glDeleteQueriesARB_getArg1Size(GLsizei, const GLuint *);
DBGLIBLOCAL int glShaderSourceARB_getArg2Size(GLhandleARB, GLsizei, const GLcharARB* *, const GLint *);
DBGLIBLOCAL int glShaderSourceARB_getArg3Size(GLhandleARB, GLsizei, const GLcharARB* *, const GLint *);
DBGLIBLOCAL int glBindAttribLocationARB_getArg2Size(GLhandleARB, GLuint, const GLcharARB *);
DBGLIBLOCAL int glDrawBuffersARB_getArg1Size(GLsizei, const GLenum *);
DBGLIBLOCAL int glTexImage3DEXT_getArg9Size(GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
DBGLIBLOCAL int glTexSubImage3DEXT_getArg10Size(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
DBGLIBLOCAL int glTexFilterFuncSGIS_getArg3Size(GLenum, GLenum, GLsizei, const GLfloat *);
DBGLIBLOCAL int glTexSubImage1DEXT_getArg6Size(GLenum, GLint, GLint, GLsizei, GLenum, GLenum, const GLvoid *);
DBGLIBLOCAL int glTexSubImage2DEXT_getArg8Size(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
DBGLIBLOCAL int glConvolutionFilter1DEXT_getArg5Size(GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *);
DBGLIBLOCAL int glConvolutionFilter2DEXT_getArg6Size(GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
DBGLIBLOCAL int glConvolutionParameterfvEXT_getArg2Size(GLenum, GLenum, const GLfloat *);
DBGLIBLOCAL int glConvolutionParameterivEXT_getArg2Size(GLenum, GLenum, const GLint *);
DBGLIBLOCAL int glSeparableFilter2DEXT_getArg6Size(GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *, const GLvoid *);
DBGLIBLOCAL int glSeparableFilter2DEXT_getArg7Size(GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *, const GLvoid *);
DBGLIBLOCAL int glColorTableSGI_getArg5Size(GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *);
DBGLIBLOCAL int glColorTableParameterfvSGI_getArg2Size(GLenum, GLenum, const GLfloat *);
DBGLIBLOCAL int glColorTableParameterivSGI_getArg2Size(GLenum, GLenum, const GLint *);
DBGLIBLOCAL int glPixelTexGenParameterivSGIS_getArg1Size(GLenum, const GLint *);
DBGLIBLOCAL int glPixelTexGenParameterfvSGIS_getArg1Size(GLenum, const GLfloat *);
DBGLIBLOCAL int glTexImage4DSGIS_getArg10Size(GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
DBGLIBLOCAL int glTexSubImage4DSGIS_getArg12Size(GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
DBGLIBLOCAL int glDeleteTexturesEXT_getArg1Size(GLsizei, const GLuint *);
DBGLIBLOCAL int glPrioritizeTexturesEXT_getArg1Size(GLsizei, const GLuint *, const GLclampf *);
DBGLIBLOCAL int glPrioritizeTexturesEXT_getArg2Size(GLsizei, const GLuint *, const GLclampf *);
DBGLIBLOCAL int glDetailTexFuncSGIS_getArg2Size(GLenum, GLsizei, const GLfloat *);
DBGLIBLOCAL int glSharpenTexFuncSGIS_getArg2Size(GLenum, GLsizei, const GLfloat *);
DBGLIBLOCAL int glColorPointerEXT_getArg4Size(GLint, GLenum, GLsizei, GLsizei, const GLvoid *);
DBGLIBLOCAL int glEdgeFlagPointerEXT_getArg2Size(GLsizei, GLsizei, const GLboolean *);
DBGLIBLOCAL int glIndexPointerEXT_getArg3Size(GLenum, GLsizei, GLsizei, const GLvoid *);
DBGLIBLOCAL int glNormalPointerEXT_getArg3Size(GLenum, GLsizei, GLsizei, const GLvoid *);
DBGLIBLOCAL int glTexCoordPointerEXT_getArg4Size(GLint, GLenum, GLsizei, GLsizei, const GLvoid *);
DBGLIBLOCAL int glVertexPointerEXT_getArg4Size(GLint, GLenum, GLsizei, GLsizei, const GLvoid *);
DBGLIBLOCAL int glSpriteParameterfvSGIX_getArg1Size(GLenum, const GLfloat *);
DBGLIBLOCAL int glSpriteParameterivSGIX_getArg1Size(GLenum, const GLint *);
DBGLIBLOCAL int glPointParameterfvEXT_getArg1Size(GLenum, const GLfloat *);
DBGLIBLOCAL int glPointParameterfvSGIS_getArg1Size(GLenum, const GLfloat *);
DBGLIBLOCAL int glInstrumentsBufferSGIX_getArg1Size(GLsizei, GLint *);
DBGLIBLOCAL int glPollInstrumentsSGIX_getArg0Size(GLint *);
DBGLIBLOCAL int glDeformationMap3dSGIX_getArg13Size(GLenum, GLdouble, GLdouble, GLint, GLint, GLdouble, GLdouble, GLint, GLint, GLdouble, GLdouble, GLint, GLint, const GLdouble *);
DBGLIBLOCAL int glDeformationMap3fSGIX_getArg13Size(GLenum, GLfloat, GLfloat, GLint, GLint, GLfloat, GLfloat, GLint, GLint, GLfloat, GLfloat, GLint, GLint, const GLfloat *);
DBGLIBLOCAL int glReferencePlaneSGIX_getArg0Size(const GLdouble *);
DBGLIBLOCAL int glFogFuncSGIS_getArg1Size(GLsizei, const GLfloat *);
DBGLIBLOCAL int glImageTransformParameterivHP_getArg2Size(GLenum, GLenum, const GLint *);
DBGLIBLOCAL int glImageTransformParameterfvHP_getArg2Size(GLenum, GLenum, const GLfloat *);
DBGLIBLOCAL int glColorSubTableEXT_getArg5Size(GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
DBGLIBLOCAL int glColorTableEXT_getArg5Size(GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *);
DBGLIBLOCAL int glListParameterfvSGIX_getArg2Size(GLuint, GLenum, const GLfloat *);
DBGLIBLOCAL int glListParameterivSGIX_getArg2Size(GLuint, GLenum, const GLint *);
DBGLIBLOCAL int glCullParameterdvEXT_getArg1Size(GLenum, GLdouble *);
DBGLIBLOCAL int glCullParameterfvEXT_getArg1Size(GLenum, GLfloat *);
DBGLIBLOCAL int glFragmentLightfvSGIX_getArg2Size(GLenum, GLenum, const GLfloat *);
DBGLIBLOCAL int glFragmentLightivSGIX_getArg2Size(GLenum, GLenum, const GLint *);
DBGLIBLOCAL int glFragmentLightModelfvSGIX_getArg1Size(GLenum, const GLfloat *);
DBGLIBLOCAL int glFragmentLightModelivSGIX_getArg1Size(GLenum, const GLint *);
DBGLIBLOCAL int glFragmentMaterialfvSGIX_getArg2Size(GLenum, GLenum, const GLfloat *);
DBGLIBLOCAL int glFragmentMaterialivSGIX_getArg2Size(GLenum, GLenum, const GLint *);
DBGLIBLOCAL int glDrawRangeElementsEXT_getArg5Size(GLenum, GLuint, GLuint, GLsizei, GLenum, const GLvoid *);
DBGLIBLOCAL int glFinishAsyncSGIX_getArg0Size(GLuint *);
DBGLIBLOCAL int glPollAsyncSGIX_getArg0Size(GLuint *);
DBGLIBLOCAL int glVertexPointervINTEL_getArg2Size(GLint, GLenum, const GLvoid* *);
DBGLIBLOCAL int glNormalPointervINTEL_getArg1Size(GLenum, const GLvoid* *);
DBGLIBLOCAL int glColorPointervINTEL_getArg2Size(GLint, GLenum, const GLvoid* *);
DBGLIBLOCAL int glTexCoordPointervINTEL_getArg2Size(GLint, GLenum, const GLvoid* *);
DBGLIBLOCAL int glPixelTransformParameterivEXT_getArg2Size(GLenum, GLenum, const GLint *);
DBGLIBLOCAL int glPixelTransformParameterfvEXT_getArg2Size(GLenum, GLenum, const GLfloat *);
DBGLIBLOCAL int glSecondaryColorPointerEXT_getArg3Size(GLint, GLenum, GLsizei, const GLvoid *);
DBGLIBLOCAL int glMultiDrawArraysEXT_getArg1Size(GLenum, GLint *, GLsizei *, GLsizei);
DBGLIBLOCAL int glMultiDrawArraysEXT_getArg2Size(GLenum, GLint *, GLsizei *, GLsizei);
DBGLIBLOCAL int glMultiDrawElementsEXT_getArg1Size(GLenum, const GLsizei *, GLenum, const GLvoid* *, GLsizei);
DBGLIBLOCAL int glMultiDrawElementsEXT_getArg3Size(GLenum, const GLsizei *, GLenum, const GLvoid* *, GLsizei);
DBGLIBLOCAL int glFogCoordfvEXT_getArg0Size(const GLfloat *);
DBGLIBLOCAL int glFogCoorddvEXT_getArg0Size(const GLdouble *);
DBGLIBLOCAL int glFogCoordPointerEXT_getArg2Size(GLenum, GLsizei, const GLvoid *);
DBGLIBLOCAL int glTangentPointerEXT_getArg2Size(GLenum, GLsizei, const GLvoid *);
DBGLIBLOCAL int glBinormalPointerEXT_getArg2Size(GLenum, GLsizei, const GLvoid *);
DBGLIBLOCAL int glReplacementCodeuivSUN_getArg0Size(const GLuint *);
DBGLIBLOCAL int glReplacementCodeusvSUN_getArg0Size(const GLushort *);
DBGLIBLOCAL int glReplacementCodeubvSUN_getArg0Size(const GLubyte *);
DBGLIBLOCAL int glReplacementCodePointerSUN_getArg2Size(GLenum, GLsizei, const GLvoid* *);
DBGLIBLOCAL int glColor4ubVertex2fvSUN_getArg0Size(const GLubyte *, const GLfloat *);
DBGLIBLOCAL int glColor4ubVertex2fvSUN_getArg1Size(const GLubyte *, const GLfloat *);
DBGLIBLOCAL int glColor4ubVertex3fvSUN_getArg0Size(const GLubyte *, const GLfloat *);
DBGLIBLOCAL int glColor4ubVertex3fvSUN_getArg1Size(const GLubyte *, const GLfloat *);
DBGLIBLOCAL int glColor3fVertex3fvSUN_getArg0Size(const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glColor3fVertex3fvSUN_getArg1Size(const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glNormal3fVertex3fvSUN_getArg0Size(const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glNormal3fVertex3fvSUN_getArg1Size(const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glColor4fNormal3fVertex3fvSUN_getArg0Size(const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glColor4fNormal3fVertex3fvSUN_getArg1Size(const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glColor4fNormal3fVertex3fvSUN_getArg2Size(const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glTexCoord2fVertex3fvSUN_getArg0Size(const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glTexCoord2fVertex3fvSUN_getArg1Size(const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glTexCoord4fVertex4fvSUN_getArg0Size(const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glTexCoord4fVertex4fvSUN_getArg1Size(const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glTexCoord2fColor4ubVertex3fvSUN_getArg0Size(const GLfloat *, const GLubyte *, const GLfloat *);
DBGLIBLOCAL int glTexCoord2fColor4ubVertex3fvSUN_getArg1Size(const GLfloat *, const GLubyte *, const GLfloat *);
DBGLIBLOCAL int glTexCoord2fColor4ubVertex3fvSUN_getArg2Size(const GLfloat *, const GLubyte *, const GLfloat *);
DBGLIBLOCAL int glTexCoord2fColor3fVertex3fvSUN_getArg0Size(const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glTexCoord2fColor3fVertex3fvSUN_getArg1Size(const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glTexCoord2fColor3fVertex3fvSUN_getArg2Size(const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glTexCoord2fNormal3fVertex3fvSUN_getArg0Size(const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glTexCoord2fNormal3fVertex3fvSUN_getArg1Size(const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glTexCoord2fNormal3fVertex3fvSUN_getArg2Size(const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glTexCoord2fColor4fNormal3fVertex3fvSUN_getArg0Size(const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glTexCoord2fColor4fNormal3fVertex3fvSUN_getArg1Size(const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glTexCoord2fColor4fNormal3fVertex3fvSUN_getArg2Size(const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glTexCoord2fColor4fNormal3fVertex3fvSUN_getArg3Size(const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glTexCoord4fColor4fNormal3fVertex4fvSUN_getArg0Size(const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glTexCoord4fColor4fNormal3fVertex4fvSUN_getArg1Size(const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glTexCoord4fColor4fNormal3fVertex4fvSUN_getArg2Size(const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glTexCoord4fColor4fNormal3fVertex4fvSUN_getArg3Size(const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiColor4ubVertex3fvSUN_getArg0Size(const GLuint *, const GLubyte *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiColor4ubVertex3fvSUN_getArg1Size(const GLuint *, const GLubyte *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiColor4ubVertex3fvSUN_getArg2Size(const GLuint *, const GLubyte *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiColor3fVertex3fvSUN_getArg0Size(const GLuint *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiColor3fVertex3fvSUN_getArg1Size(const GLuint *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiColor3fVertex3fvSUN_getArg2Size(const GLuint *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiNormal3fVertex3fvSUN_getArg0Size(const GLuint *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiNormal3fVertex3fvSUN_getArg1Size(const GLuint *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiNormal3fVertex3fvSUN_getArg2Size(const GLuint *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiColor4fNormal3fVertex3fvSUN_getArg0Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiColor4fNormal3fVertex3fvSUN_getArg1Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiColor4fNormal3fVertex3fvSUN_getArg2Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiColor4fNormal3fVertex3fvSUN_getArg3Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiTexCoord2fVertex3fvSUN_getArg0Size(const GLuint *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiTexCoord2fVertex3fvSUN_getArg1Size(const GLuint *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiTexCoord2fVertex3fvSUN_getArg2Size(const GLuint *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN_getArg0Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN_getArg1Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN_getArg2Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN_getArg3Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN_getArg0Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN_getArg1Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN_getArg2Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN_getArg3Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN_getArg4Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
DBGLIBLOCAL int glVertexWeightfvEXT_getArg0Size(const GLfloat *);
DBGLIBLOCAL int glVertexWeightPointerEXT_getArg3Size(GLsizei, GLenum, GLsizei, const GLvoid *);
DBGLIBLOCAL int glVertexArrayRangeNV_getArg1Size(GLsizei, const GLvoid *);
DBGLIBLOCAL int glCombinerParameterfvNV_getArg1Size(GLenum, const GLfloat *);
DBGLIBLOCAL int glCombinerParameterivNV_getArg1Size(GLenum, const GLint *);
DBGLIBLOCAL int glMultiModeDrawArraysIBM_getArg0Size(const GLenum *, const GLint *, const GLsizei *, GLsizei, GLint);
DBGLIBLOCAL int glMultiModeDrawArraysIBM_getArg1Size(const GLenum *, const GLint *, const GLsizei *, GLsizei, GLint);
DBGLIBLOCAL int glMultiModeDrawArraysIBM_getArg2Size(const GLenum *, const GLint *, const GLsizei *, GLsizei, GLint);
DBGLIBLOCAL int glMultiModeDrawElementsIBM_getArg0Size(const GLenum *, const GLsizei *, GLenum, const GLvoid* const *, GLsizei, GLint);
DBGLIBLOCAL int glMultiModeDrawElementsIBM_getArg1Size(const GLenum *, const GLsizei *, GLenum, const GLvoid* const *, GLsizei, GLint);
DBGLIBLOCAL int glMultiModeDrawElementsIBM_getArg3Size(const GLenum *, const GLsizei *, GLenum, const GLvoid* const *, GLsizei, GLint);
DBGLIBLOCAL int glColorPointerListIBM_getArg3Size(GLint, GLenum, GLint, const GLvoid* *, GLint);
DBGLIBLOCAL int glSecondaryColorPointerListIBM_getArg3Size(GLint, GLenum, GLint, const GLvoid* *, GLint);
DBGLIBLOCAL int glEdgeFlagPointerListIBM_getArg1Size(GLint, const GLboolean* *, GLint);
DBGLIBLOCAL int glFogCoordPointerListIBM_getArg2Size(GLenum, GLint, const GLvoid* *, GLint);
DBGLIBLOCAL int glIndexPointerListIBM_getArg2Size(GLenum, GLint, const GLvoid* *, GLint);
DBGLIBLOCAL int glNormalPointerListIBM_getArg2Size(GLenum, GLint, const GLvoid* *, GLint);
DBGLIBLOCAL int glTexCoordPointerListIBM_getArg3Size(GLint, GLenum, GLint, const GLvoid* *, GLint);
DBGLIBLOCAL int glVertexPointerListIBM_getArg3Size(GLint, GLenum, GLint, const GLvoid* *, GLint);
DBGLIBLOCAL int glIglooInterfaceSGIX_getArg1Size(GLenum, const GLvoid *);
DBGLIBLOCAL int glDeleteFencesNV_getArg1Size(GLsizei, const GLuint *);
DBGLIBLOCAL int glMapControlPointsNV_getArg8Size(GLenum, GLuint, GLenum, GLsizei, GLsizei, GLint, GLint, GLboolean, const GLvoid *);
DBGLIBLOCAL int glMapParameterivNV_getArg2Size(GLenum, GLenum, const GLint *);
DBGLIBLOCAL int glMapParameterfvNV_getArg2Size(GLenum, GLenum, const GLfloat *);
DBGLIBLOCAL int glCombinerStageParameterfvNV_getArg2Size(GLenum, GLenum, const GLfloat *);
DBGLIBLOCAL int glDeleteProgramsNV_getArg1Size(GLsizei, const GLuint *);
DBGLIBLOCAL int glExecuteProgramNV_getArg2Size(GLenum, GLuint, const GLfloat *);
DBGLIBLOCAL int glLoadProgramNV_getArg3Size(GLenum, GLuint, GLsizei, const GLubyte *);
DBGLIBLOCAL int glRequestResidentProgramsNV_getArg1Size(GLsizei, const GLuint *);
DBGLIBLOCAL int glVertexAttribPointerNV_getArg4Size(GLuint, GLint, GLenum, GLsizei, const GLvoid *);
DBGLIBLOCAL int glTexBumpParameterivATI_getArg1Size(GLenum, const GLint *);
DBGLIBLOCAL int glTexBumpParameterfvATI_getArg1Size(GLenum, const GLfloat *);
DBGLIBLOCAL int glSetFragmentShaderConstantATI_getArg1Size(GLuint, const GLfloat *);
DBGLIBLOCAL int glNewObjectBufferATI_getArg1Size(GLsizei, const GLvoid *, GLenum);
DBGLIBLOCAL int glUpdateObjectBufferATI_getArg3Size(GLuint, GLuint, GLsizei, const GLvoid *, GLenum);
DBGLIBLOCAL int glSetInvariantEXT_getArg2Size(GLuint, GLenum, const GLvoid *);
DBGLIBLOCAL int glSetLocalConstantEXT_getArg2Size(GLuint, GLenum, const GLvoid *);
DBGLIBLOCAL int glVariantbvEXT_getArg1Size(GLuint, const GLbyte *);
DBGLIBLOCAL int glVariantsvEXT_getArg1Size(GLuint, const GLshort *);
DBGLIBLOCAL int glVariantivEXT_getArg1Size(GLuint, const GLint *);
DBGLIBLOCAL int glVariantfvEXT_getArg1Size(GLuint, const GLfloat *);
DBGLIBLOCAL int glVariantdvEXT_getArg1Size(GLuint, const GLdouble *);
DBGLIBLOCAL int glVariantubvEXT_getArg1Size(GLuint, const GLubyte *);
DBGLIBLOCAL int glVariantusvEXT_getArg1Size(GLuint, const GLushort *);
DBGLIBLOCAL int glVariantuivEXT_getArg1Size(GLuint, const GLuint *);
DBGLIBLOCAL int glVariantPointerEXT_getArg3Size(GLuint, GLenum, GLuint, const GLvoid *);
DBGLIBLOCAL int glElementPointerATI_getArg1Size(GLenum, const GLvoid *);
DBGLIBLOCAL int glDeleteOcclusionQueriesNV_getArg1Size(GLsizei, const GLuint *);
DBGLIBLOCAL int glPointParameterivNV_getArg1Size(GLenum, const GLint *);
DBGLIBLOCAL int glElementPointerAPPLE_getArg1Size(GLenum, const GLvoid *);
DBGLIBLOCAL int glMultiDrawElementArrayAPPLE_getArg1Size(GLenum, const GLint *, const GLsizei *, GLsizei);
DBGLIBLOCAL int glMultiDrawElementArrayAPPLE_getArg2Size(GLenum, const GLint *, const GLsizei *, GLsizei);
DBGLIBLOCAL int glMultiDrawRangeElementArrayAPPLE_getArg3Size(GLenum, GLuint, GLuint, const GLint *, const GLsizei *, GLsizei);
DBGLIBLOCAL int glMultiDrawRangeElementArrayAPPLE_getArg4Size(GLenum, GLuint, GLuint, const GLint *, const GLsizei *, GLsizei);
DBGLIBLOCAL int glDeleteFencesAPPLE_getArg1Size(GLsizei, const GLuint *);
DBGLIBLOCAL int glDeleteVertexArraysAPPLE_getArg1Size(GLsizei, const GLuint *);
DBGLIBLOCAL int glVertexArrayRangeAPPLE_getArg1Size(GLsizei, GLvoid *);
DBGLIBLOCAL int glFlushVertexArrayRangeAPPLE_getArg1Size(GLsizei, GLvoid *);
DBGLIBLOCAL int glDrawBuffersATI_getArg1Size(GLsizei, const GLenum *);
DBGLIBLOCAL int glProgramNamedParameter4fNV_getArg2Size(GLuint, GLsizei, const GLubyte *, GLfloat, GLfloat, GLfloat, GLfloat);
DBGLIBLOCAL int glProgramNamedParameter4dNV_getArg2Size(GLuint, GLsizei, const GLubyte *, GLdouble, GLdouble, GLdouble, GLdouble);
DBGLIBLOCAL int glFogCoordhvNV_getArg0Size(const GLhalfNV *);
DBGLIBLOCAL int glVertexWeighthvNV_getArg0Size(const GLhalfNV *);
DBGLIBLOCAL int glPixelDataRangeNV_getArg2Size(GLenum, GLsizei, GLvoid *);
DBGLIBLOCAL int glDeleteRenderbuffersEXT_getArg1Size(GLsizei, const GLuint *);
DBGLIBLOCAL int glDeleteFramebuffersEXT_getArg1Size(GLsizei, const GLuint *);
DBGLIBLOCAL int glStringMarkerGREMEDY_getArg1Size(GLsizei, const GLvoid *);
DBGLIBLOCAL int glTransformFeedbackAttribsNV_getArg1Size(GLuint count, const GLint *attribs, GLenum bufferMode);
DBGLIBLOCAL int glTransformFeedbackVaryingsNV_getArg2Size(GLuint program, GLsizei count, const GLint *locations, GLenum bufferMode);
DBGLIBLOCAL int glActiveVaryingNV_getArg1Size(GLuint program, const GLchar *name);
DBGLIBLOCAL int glTexParameterIivEXT_getArg2Size(GLenum target, GLenum pname, const GLint *params);
DBGLIBLOCAL int glTexParameterIuivEXT_getArg2Size(GLenum target, GLenum pname, const GLuint *params);
DBGLIBLOCAL int glBindFragDataLocationEXT_getArg2Size(GLuint program, GLuint color, const GLchar *name);
DBGLIBLOCAL int glVertexAttribIPointerEXT_getArg4Size(GLuint index, GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
DBGLIBLOCAL int glProgramBufferParametersfvNV_getArg4Size(GLenum target, GLuint buffer, GLuint index, GLsizei count, const GLfloat *params);
DBGLIBLOCAL int glProgramBufferParametersIivNV_getArg4Size(GLenum target, GLuint buffer, GLuint index, GLsizei count, const GLint *params);
DBGLIBLOCAL int glProgramBufferParametersIuivNV_getArg4Size(GLenum target, GLuint buffer, GLuint index, GLsizei count, const GLuint *params);
DBGLIBLOCAL int glDrawElementsInstancedEXT_getArg3Size(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices, GLsizei primcount);

#else

int glBitmap_getArg6Size(GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap);
int glCallLists_getArg2Size(GLsizei n, GLenum type, const GLvoid *lists);
int glClipPlane_getArg1Size(GLenum plane, const GLdouble *equation);
int glColorPointer_getArg3Size(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
int glDeleteTextures_getArg1Size(GLsizei n, const GLuint *textures);
int glDrawElements_getArg3Size(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices);
int glDrawPixels_getArg4Size(GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
int glEdgeFlagPointer_getArg1Size(GLsizei stride, const GLvoid *pointer);
int glEdgeFlagv_getArg0Size(const GLboolean *flag);
int glFeedbackBuffer_getArg2Size(GLsizei size, GLenum type, GLfloat *buffer);
int glFogfv_getArg1Size(GLenum pname, const GLfloat *params);
int glFogiv_getArg1Size(GLenum pname, const GLint *params);
int glIndexPointer_getArg2Size(GLenum type, GLsizei stride, const GLvoid *pointer);
int glIndexdv_getArg0Size(const GLdouble *c);
int glIndexfv_getArg0Size(const GLfloat *c);
int glIndexiv_getArg0Size(const GLint *c);
int glIndexsv_getArg0Size(const GLshort *c);
int glIndexubv_getArg0Size(const GLubyte *c);
int glInterleavedArrays_getArg2Size(GLenum format, GLsizei stride, const GLvoid *pointer);
int glLightModelfv_getArg1Size(GLenum pname, const GLfloat *params);
int glLightModeliv_getArg1Size(GLenum pname, const GLint *params);
int glLightfv_getArg2Size(GLenum light, GLenum pname, const GLfloat *params);
int glLightiv_getArg2Size(GLenum light, GLenum pname, const GLint *params);
int glLoadMatrixd_getArg0Size(const GLdouble *m);
int glLoadMatrixf_getArg0Size(const GLfloat *m);
int glMap1d_getArg5Size(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points);
int glMap1f_getArg5Size(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points);
int glMap2d_getArg9Size(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points);
int glMap2f_getArg9Size(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points);
int glMaterialfv_getArg2Size(GLenum face, GLenum pname, const GLfloat *params);
int glMaterialiv_getArg2Size(GLenum face, GLenum pname, const GLint *params);
int glMultMatrixd_getArg0Size(const GLdouble *m);
int glMultMatrixf_getArg0Size(const GLfloat *m);
int glNormalPointer_getArg2Size(GLenum type, GLsizei stride, const GLvoid *pointer);
int glPixelMapfv_getArg2Size(GLenum map, GLsizei mapsize, const GLfloat *values);
int glPixelMapuiv_getArg2Size(GLenum map, GLsizei mapsize, const GLuint *values);
int glPixelMapusv_getArg2Size(GLenum map, GLsizei mapsize, const GLushort *values);
int glPolygonStipple_getArg0Size(const GLubyte *mask);
int glPrioritizeTextures_getArg1Size(GLsizei n, const GLuint *textures, const GLclampf *priorities);
int glPrioritizeTextures_getArg2Size(GLsizei n, const GLuint *textures, const GLclampf *priorities);
int glReadPixels_getArg6Size(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels);
int glRectdv_getArg0Size(const GLdouble *v1, const GLdouble *v2);
int glRectdv_getArg1Size(const GLdouble *v1, const GLdouble *v2);
int glRectfv_getArg0Size(const GLfloat *v1, const GLfloat *v2);
int glRectfv_getArg1Size(const GLfloat *v1, const GLfloat *v2);
int glRectiv_getArg0Size(const GLint *v1, const GLint *v2);
int glRectiv_getArg1Size(const GLint *v1, const GLint *v2);
int glRectsv_getArg0Size(const GLshort *v1, const GLshort *v2);
int glRectsv_getArg1Size(const GLshort *v1, const GLshort *v2);
int glSelectBuffer_getArg1Size(GLsizei size, GLuint *buffer);
int glTexCoordPointer_getArg3Size(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
int glTexEnvfv_getArg2Size(GLenum target, GLenum pname, const GLfloat *params);
int glTexEnviv_getArg2Size(GLenum target, GLenum pname, const GLint *params);
int glTexGendv_getArg2Size(GLenum coord, GLenum pname, const GLdouble *params);
int glTexGenfv_getArg2Size(GLenum coord, GLenum pname, const GLfloat *params);
int glTexGeniv_getArg2Size(GLenum coord, GLenum pname, const GLint *params);
int glTexImage1D_getArg7Size(GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
int glTexImage2D_getArg8Size(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
int glTexParameterfv_getArg2Size(GLenum target, GLenum pname, const GLfloat *params);
int glTexParameteriv_getArg2Size(GLenum target, GLenum pname, const GLint *params);
int glTexSubImage1D_getArg6Size(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels);
int glTexSubImage2D_getArg8Size(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
int glVertexPointer_getArg3Size(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
int glDrawRangeElements_getArg5Size(GLenum, GLuint, GLuint, GLsizei, GLenum, const GLvoid *);
int glTexImage3D_getArg9Size(GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
int glTexSubImage3D_getArg10Size(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
int glColorTable_getArg5Size(GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *);
int glColorTableParameterfv_getArg2Size(GLenum, GLenum, const GLfloat *);
int glColorTableParameteriv_getArg2Size(GLenum, GLenum, const GLint *);
int glColorSubTable_getArg5Size(GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
int glConvolutionFilter1D_getArg5Size(GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *);
int glConvolutionFilter2D_getArg6Size(GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
int glConvolutionParameterfv_getArg2Size(GLenum, GLenum, const GLfloat *);
int glConvolutionParameteriv_getArg2Size(GLenum, GLenum, const GLint *);
int glSeparableFilter2D_getArg6Size(GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *, const GLvoid *);
int glSeparableFilter2D_getArg7Size(GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *, const GLvoid *);
int glCompressedTexImage3D_getArg8Size(GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *);
int glCompressedTexImage2D_getArg7Size(GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *);
int glCompressedTexImage1D_getArg6Size(GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, const GLvoid *);
int glCompressedTexSubImage3D_getArg10Size(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *);
int glCompressedTexSubImage2D_getArg8Size(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *);
int glCompressedTexSubImage1D_getArg6Size(GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, const GLvoid *);
int glLoadTransposeMatrixf_getArg0Size(const GLfloat *);
int glLoadTransposeMatrixd_getArg0Size(const GLdouble *);
int glMultTransposeMatrixf_getArg0Size(const GLfloat *);
int glMultTransposeMatrixd_getArg0Size(const GLdouble *);
int glMultiDrawArrays_getArg1Size(GLenum, GLint *, GLsizei *, GLsizei);
int glMultiDrawArrays_getArg2Size(GLenum, GLint *, GLsizei *, GLsizei);
int glMultiDrawElements_getArg1Size(GLenum, const GLsizei *, GLenum, const GLvoid* *, GLsizei);
int glMultiDrawElements_getArg3Size(GLenum, const GLsizei *, GLenum, const GLvoid* *, GLsizei);
int glPointParameterfv_getArg1Size(GLenum, const GLfloat *);
int glPointParameteriv_getArg1Size(GLenum, const GLint *);
int glFogCoordfv_getArg0Size(const GLfloat *);
int glFogCoorddv_getArg0Size(const GLdouble *);
int glFogCoordPointer_getArg2Size(GLenum, GLsizei, const GLvoid *);
int glSecondaryColorPointer_getArg3Size(GLint, GLenum, GLsizei, const GLvoid *);
int glDeleteQueries_getArg1Size(GLsizei, const GLuint *);
int glDeleteBuffers_getArg1Size(GLsizei, const GLuint *);
int glBufferData_getArg2Size(GLenum, GLsizeiptr, const GLvoid *, GLenum);
int glBufferSubData_getArg3Size(GLenum, GLintptr, GLsizeiptr, const GLvoid *);
int glDrawBuffers_getArg1Size(GLsizei, const GLenum *);
int glBindAttribLocation_getArg2Size(GLuint, GLuint, const GLchar *);
int glShaderSource_getArg2Size(GLuint, GLsizei, const GLchar* *, const GLint *);
int glShaderSource_getArg3Size(GLuint, GLsizei, const GLchar* *, const GLint *);
int glVertexAttrib4Nubv_getArg1Size(GLuint, const GLubyte *);
int glVertexAttrib4Nuiv_getArg1Size(GLuint, const GLuint *);
int glVertexAttrib4Nusv_getArg1Size(GLuint, const GLushort *);
int glVertexAttribPointer_getArg5Size(GLuint, GLint, GLenum, GLboolean, GLsizei, const GLvoid *);
int glUniformMatrix2x3fv_getArg3Size(GLint, GLsizei, GLboolean, const GLfloat *);
int glUniformMatrix3x2fv_getArg3Size(GLint, GLsizei, GLboolean, const GLfloat *);
int glUniformMatrix2x4fv_getArg3Size(GLint, GLsizei, GLboolean, const GLfloat *);
int glUniformMatrix4x2fv_getArg3Size(GLint, GLsizei, GLboolean, const GLfloat *);
int glUniformMatrix3x4fv_getArg3Size(GLint, GLsizei, GLboolean, const GLfloat *);
int glUniformMatrix4x3fv_getArg3Size(GLint, GLsizei, GLboolean, const GLfloat *);
/* NEW FUNCTIONS */
int glTransformFeedbackVaryings_getArg2Size(GLuint, GLsizei, const GLchar* *, GLenum);
int glVertexAttribIPointer_getArg4Size(GLuint, GLint, GLenum, GLsizei, const GLvoid *);
int glBindFragDataLocation_getArg2Size(GLuint, GLuint, const GLchar *);
int glTexParameterIiv_getArg2Size(GLenum, GLenum, const GLint *);
int glTexParameterIuiv_getArg2Size(GLenum, GLenum, const GLuint *);
int glClearBufferiv_getArg2Size(GLenum, GLint, const GLint *);
int glClearBufferuiv_getArg2Size(GLenum, GLint, const GLuint *);
int glClearBufferfv_getArg2Size(GLenum, GLint, const GLfloat *);
int glDrawElementsInstanced_getArg3Size(GLenum, GLsizei, GLenum, const GLvoid *, GLsizei);
/* NEW FUNCTIONS */
int glLoadTransposeMatrixfARB_getArg0Size(const GLfloat *);
int glLoadTransposeMatrixdARB_getArg0Size(const GLdouble *);
int glMultTransposeMatrixfARB_getArg0Size(const GLfloat *);
int glMultTransposeMatrixdARB_getArg0Size(const GLdouble *);
int glCompressedTexImage3DARB_getArg8Size(GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *);
int glCompressedTexImage2DARB_getArg7Size(GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *);
int glCompressedTexImage1DARB_getArg6Size(GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, const GLvoid *);
int glCompressedTexSubImage3DARB_getArg10Size(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *);
int glCompressedTexSubImage2DARB_getArg8Size(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *);
int glCompressedTexSubImage1DARB_getArg6Size(GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, const GLvoid *);
int glPointParameterfvARB_getArg1Size(GLenum, const GLfloat *);
int glWeightbvARB_getArg1Size(GLint, const GLbyte *);
int glWeightsvARB_getArg1Size(GLint, const GLshort *);
int glWeightivARB_getArg1Size(GLint, const GLint *);
int glWeightfvARB_getArg1Size(GLint, const GLfloat *);
int glWeightdvARB_getArg1Size(GLint, const GLdouble *);
int glWeightubvARB_getArg1Size(GLint, const GLubyte *);
int glWeightusvARB_getArg1Size(GLint, const GLushort *);
int glWeightuivARB_getArg1Size(GLint, const GLuint *);
int glWeightPointerARB_getArg3Size(GLint, GLenum, GLsizei, const GLvoid *);
int glMatrixIndexubvARB_getArg1Size(GLint, const GLubyte *);
int glMatrixIndexusvARB_getArg1Size(GLint, const GLushort *);
int glMatrixIndexuivARB_getArg1Size(GLint, const GLuint *);
int glMatrixIndexPointerARB_getArg3Size(GLint, GLenum, GLsizei, const GLvoid *);
int glVertexAttrib4NubvARB_getArg1Size(GLuint, const GLubyte *);
int glVertexAttrib4NuivARB_getArg1Size(GLuint, const GLuint *);
int glVertexAttrib4NusvARB_getArg1Size(GLuint, const GLushort *);
int glVertexAttribPointerARB_getArg5Size(GLuint, GLint, GLenum, GLboolean, GLsizei, const GLvoid *);
int glProgramStringARB_getArg3Size(GLenum, GLenum, GLsizei, const GLvoid *);
int glDeleteProgramsARB_getArg1Size(GLsizei, const GLuint *);
int glDeleteBuffersARB_getArg1Size(GLsizei, const GLuint *);
int glBufferDataARB_getArg2Size(GLenum, GLsizeiptrARB, const GLvoid *, GLenum);
int glBufferSubDataARB_getArg3Size(GLenum, GLintptrARB, GLsizeiptrARB, const GLvoid *);
int glDeleteQueriesARB_getArg1Size(GLsizei, const GLuint *);
int glShaderSourceARB_getArg2Size(GLhandleARB, GLsizei, const GLcharARB* *, const GLint *);
int glShaderSourceARB_getArg3Size(GLhandleARB, GLsizei, const GLcharARB* *, const GLint *);
int glBindAttribLocationARB_getArg2Size(GLhandleARB, GLuint, const GLcharARB *);
int glDrawBuffersARB_getArg1Size(GLsizei, const GLenum *);
/* NEW FUNCTIONS */
int glDrawElementsInstancedARB_getArg3Size(GLenum, GLsizei, GLenum, const GLvoid *, GLsizei);
int glDeleteRenderbuffers_getArg1Size(GLsizei, const GLuint *);
int glDeleteFramebuffers_getArg1Size(GLsizei, const GLuint *);
int glDeleteVertexArrays_getArg1Size(GLsizei, const GLuint *);
int glDrawElementsBaseVertex_getArg3Size(GLenum, GLsizei, GLenum, const GLvoid *, GLint);
int glDrawRangeElementsBaseVertex_getArg5Size(GLenum, GLuint, GLuint, GLsizei, GLenum, const GLvoid *, GLint);
int glDrawElementsInstancedBaseVertex_getArg3Size(GLenum, GLsizei, GLenum, const GLvoid *, GLsizei, GLint);
int glMultiDrawElementsBaseVertex_getArg1Size(GLenum, const GLsizei *, GLenum, const GLvoid* *, GLsizei, const GLint *);
int glMultiDrawElementsBaseVertex_getArg3Size(GLenum, const GLsizei *, GLenum, const GLvoid* *, GLsizei, const GLint *);
int glMultiDrawElementsBaseVertex_getArg5Size(GLenum, const GLsizei *, GLenum, const GLvoid* *, GLsizei, const GLint *);
/* NEW FUNCTIONS */
int glTexImage3DEXT_getArg9Size(GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
int glTexSubImage3DEXT_getArg10Size(GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
int glTexFilterFuncSGIS_getArg3Size(GLenum, GLenum, GLsizei, const GLfloat *);
int glTexSubImage1DEXT_getArg6Size(GLenum, GLint, GLint, GLsizei, GLenum, GLenum, const GLvoid *);
int glTexSubImage2DEXT_getArg8Size(GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
int glConvolutionFilter1DEXT_getArg5Size(GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *);
int glConvolutionFilter2DEXT_getArg6Size(GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
int glConvolutionParameterfvEXT_getArg2Size(GLenum, GLenum, const GLfloat *);
int glConvolutionParameterivEXT_getArg2Size(GLenum, GLenum, const GLint *);
int glSeparableFilter2DEXT_getArg6Size(GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *, const GLvoid *);
int glSeparableFilter2DEXT_getArg7Size(GLenum, GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *, const GLvoid *);
int glColorTableSGI_getArg5Size(GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *);
int glColorTableParameterfvSGI_getArg2Size(GLenum, GLenum, const GLfloat *);
int glColorTableParameterivSGI_getArg2Size(GLenum, GLenum, const GLint *);
int glPixelTexGenParameterivSGIS_getArg1Size(GLenum, const GLint *);
int glPixelTexGenParameterfvSGIS_getArg1Size(GLenum, const GLfloat *);
int glTexImage4DSGIS_getArg10Size(GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
int glTexSubImage4DSGIS_getArg12Size(GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
int glDeleteTexturesEXT_getArg1Size(GLsizei, const GLuint *);
int glPrioritizeTexturesEXT_getArg1Size(GLsizei, const GLuint *, const GLclampf *);
int glPrioritizeTexturesEXT_getArg2Size(GLsizei, const GLuint *, const GLclampf *);
int glDetailTexFuncSGIS_getArg2Size(GLenum, GLsizei, const GLfloat *);
int glSharpenTexFuncSGIS_getArg2Size(GLenum, GLsizei, const GLfloat *);
int glColorPointerEXT_getArg4Size(GLint, GLenum, GLsizei, GLsizei, const GLvoid *);
int glEdgeFlagPointerEXT_getArg2Size(GLsizei, GLsizei, const GLboolean *);
int glIndexPointerEXT_getArg3Size(GLenum, GLsizei, GLsizei, const GLvoid *);
int glNormalPointerEXT_getArg3Size(GLenum, GLsizei, GLsizei, const GLvoid *);
int glTexCoordPointerEXT_getArg4Size(GLint, GLenum, GLsizei, GLsizei, const GLvoid *);
int glVertexPointerEXT_getArg4Size(GLint, GLenum, GLsizei, GLsizei, const GLvoid *);
int glSpriteParameterfvSGIX_getArg1Size(GLenum, const GLfloat *);
int glSpriteParameterivSGIX_getArg1Size(GLenum, const GLint *);
int glPointParameterfvEXT_getArg1Size(GLenum, const GLfloat *);
int glPointParameterfvSGIS_getArg1Size(GLenum, const GLfloat *);
int glInstrumentsBufferSGIX_getArg1Size(GLsizei, GLint *);
int glPollInstrumentsSGIX_getArg0Size(GLint *);
int glDeformationMap3dSGIX_getArg13Size(GLenum, GLdouble, GLdouble, GLint, GLint, GLdouble, GLdouble, GLint, GLint, GLdouble, GLdouble, GLint, GLint, const GLdouble *);
int glDeformationMap3fSGIX_getArg13Size(GLenum, GLfloat, GLfloat, GLint, GLint, GLfloat, GLfloat, GLint, GLint, GLfloat, GLfloat, GLint, GLint, const GLfloat *);
int glReferencePlaneSGIX_getArg0Size(const GLdouble *);
int glFogFuncSGIS_getArg1Size(GLsizei, const GLfloat *);
int glImageTransformParameterivHP_getArg2Size(GLenum, GLenum, const GLint *);
int glImageTransformParameterfvHP_getArg2Size(GLenum, GLenum, const GLfloat *);
int glColorSubTableEXT_getArg5Size(GLenum, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
int glColorTableEXT_getArg5Size(GLenum, GLenum, GLsizei, GLenum, GLenum, const GLvoid *);
int glListParameterfvSGIX_getArg2Size(GLuint, GLenum, const GLfloat *);
int glListParameterivSGIX_getArg2Size(GLuint, GLenum, const GLint *);
int glCullParameterdvEXT_getArg1Size(GLenum, GLdouble *);
int glCullParameterfvEXT_getArg1Size(GLenum, GLfloat *);
int glFragmentLightfvEXT_getArg2Size(GLenum, GLenum, const GLfloat *);
int glFragmentLightivEXT_getArg2Size(GLenum, GLenum, const GLint *);
int glFragmentLightModelfvEXT_getArg1Size(GLenum, const GLfloat *);
int glFragmentLightModelivEXT_getArg1Size(GLenum, const GLint *);
int glFragmentMaterialfvEXT_getArg2Size(GLenum, GLenum, const GLfloat *);
int glFragmentMaterialivEXT_getArg2Size(GLenum, GLenum, const GLint *);
int glDrawRangeElementsEXT_getArg5Size(GLenum, GLuint, GLuint, GLsizei, GLenum, const GLvoid *);
int glFinishAsyncSGIX_getArg0Size(GLuint *);
int glPollAsyncSGIX_getArg0Size(GLuint *);
int glVertexPointervINTEL_getArg2Size(GLint, GLenum, const GLvoid* *);
int glNormalPointervINTEL_getArg1Size(GLenum, const GLvoid* *);
int glColorPointervINTEL_getArg2Size(GLint, GLenum, const GLvoid* *);
int glTexCoordPointervINTEL_getArg2Size(GLint, GLenum, const GLvoid* *);
int glPixelTransformParameterivEXT_getArg2Size(GLenum, GLenum, const GLint *);
int glPixelTransformParameterfvEXT_getArg2Size(GLenum, GLenum, const GLfloat *);
int glSecondaryColorPointerEXT_getArg3Size(GLint, GLenum, GLsizei, const GLvoid *);
int glMultiDrawArraysEXT_getArg1Size(GLenum, GLint *, GLsizei *, GLsizei);
int glMultiDrawArraysEXT_getArg2Size(GLenum, GLint *, GLsizei *, GLsizei);
int glMultiDrawElementsEXT_getArg1Size(GLenum, const GLsizei *, GLenum, const GLvoid* *, GLsizei);
int glMultiDrawElementsEXT_getArg3Size(GLenum, const GLsizei *, GLenum, const GLvoid* *, GLsizei);
int glFogCoordfvEXT_getArg0Size(const GLfloat *);
int glFogCoorddvEXT_getArg0Size(const GLdouble *);
int glFogCoordPointerEXT_getArg2Size(GLenum, GLsizei, const GLvoid *);
int glTangentPointerEXT_getArg2Size(GLenum, GLsizei, const GLvoid *);
int glBinormalPointerEXT_getArg2Size(GLenum, GLsizei, const GLvoid *);
int glReplacementCodeuivSUN_getArg0Size(const GLuint *);
int glReplacementCodeusvSUN_getArg0Size(const GLushort *);
int glReplacementCodeubvSUN_getArg0Size(const GLubyte *);
int glReplacementCodePointerSUN_getArg2Size(GLenum, GLsizei, const GLvoid* *);
int glColor4ubVertex2fvSUN_getArg0Size(const GLubyte *, const GLfloat *);
int glColor4ubVertex2fvSUN_getArg1Size(const GLubyte *, const GLfloat *);
int glColor4ubVertex3fvSUN_getArg0Size(const GLubyte *, const GLfloat *);
int glColor4ubVertex3fvSUN_getArg1Size(const GLubyte *, const GLfloat *);
int glColor3fVertex3fvSUN_getArg0Size(const GLfloat *, const GLfloat *);
int glColor3fVertex3fvSUN_getArg1Size(const GLfloat *, const GLfloat *);
int glNormal3fVertex3fvSUN_getArg0Size(const GLfloat *, const GLfloat *);
int glNormal3fVertex3fvSUN_getArg1Size(const GLfloat *, const GLfloat *);
int glColor4fNormal3fVertex3fvSUN_getArg0Size(const GLfloat *, const GLfloat *, const GLfloat *);
int glColor4fNormal3fVertex3fvSUN_getArg1Size(const GLfloat *, const GLfloat *, const GLfloat *);
int glColor4fNormal3fVertex3fvSUN_getArg2Size(const GLfloat *, const GLfloat *, const GLfloat *);
int glTexCoord2fVertex3fvSUN_getArg0Size(const GLfloat *, const GLfloat *);
int glTexCoord2fVertex3fvSUN_getArg1Size(const GLfloat *, const GLfloat *);
int glTexCoord4fVertex4fvSUN_getArg0Size(const GLfloat *, const GLfloat *);
int glTexCoord4fVertex4fvSUN_getArg1Size(const GLfloat *, const GLfloat *);
int glTexCoord2fColor4ubVertex3fvSUN_getArg0Size(const GLfloat *, const GLubyte *, const GLfloat *);
int glTexCoord2fColor4ubVertex3fvSUN_getArg1Size(const GLfloat *, const GLubyte *, const GLfloat *);
int glTexCoord2fColor4ubVertex3fvSUN_getArg2Size(const GLfloat *, const GLubyte *, const GLfloat *);
int glTexCoord2fColor3fVertex3fvSUN_getArg0Size(const GLfloat *, const GLfloat *, const GLfloat *);
int glTexCoord2fColor3fVertex3fvSUN_getArg1Size(const GLfloat *, const GLfloat *, const GLfloat *);
int glTexCoord2fColor3fVertex3fvSUN_getArg2Size(const GLfloat *, const GLfloat *, const GLfloat *);
int glTexCoord2fNormal3fVertex3fvSUN_getArg0Size(const GLfloat *, const GLfloat *, const GLfloat *);
int glTexCoord2fNormal3fVertex3fvSUN_getArg1Size(const GLfloat *, const GLfloat *, const GLfloat *);
int glTexCoord2fNormal3fVertex3fvSUN_getArg2Size(const GLfloat *, const GLfloat *, const GLfloat *);
int glTexCoord2fColor4fNormal3fVertex3fvSUN_getArg0Size(const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
int glTexCoord2fColor4fNormal3fVertex3fvSUN_getArg1Size(const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
int glTexCoord2fColor4fNormal3fVertex3fvSUN_getArg2Size(const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
int glTexCoord2fColor4fNormal3fVertex3fvSUN_getArg3Size(const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
int glTexCoord4fColor4fNormal3fVertex4fvSUN_getArg0Size(const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
int glTexCoord4fColor4fNormal3fVertex4fvSUN_getArg1Size(const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
int glTexCoord4fColor4fNormal3fVertex4fvSUN_getArg2Size(const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
int glTexCoord4fColor4fNormal3fVertex4fvSUN_getArg3Size(const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiColor4ubVertex3fvSUN_getArg0Size(const GLuint *, const GLubyte *, const GLfloat *);
int glReplacementCodeuiColor4ubVertex3fvSUN_getArg1Size(const GLuint *, const GLubyte *, const GLfloat *);
int glReplacementCodeuiColor4ubVertex3fvSUN_getArg2Size(const GLuint *, const GLubyte *, const GLfloat *);
int glReplacementCodeuiColor3fVertex3fvSUN_getArg0Size(const GLuint *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiColor3fVertex3fvSUN_getArg1Size(const GLuint *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiColor3fVertex3fvSUN_getArg2Size(const GLuint *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiNormal3fVertex3fvSUN_getArg0Size(const GLuint *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiNormal3fVertex3fvSUN_getArg1Size(const GLuint *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiNormal3fVertex3fvSUN_getArg2Size(const GLuint *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiColor4fNormal3fVertex3fvSUN_getArg0Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiColor4fNormal3fVertex3fvSUN_getArg1Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiColor4fNormal3fVertex3fvSUN_getArg2Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiColor4fNormal3fVertex3fvSUN_getArg3Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiTexCoord2fVertex3fvSUN_getArg0Size(const GLuint *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiTexCoord2fVertex3fvSUN_getArg1Size(const GLuint *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiTexCoord2fVertex3fvSUN_getArg2Size(const GLuint *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN_getArg0Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN_getArg1Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN_getArg2Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN_getArg3Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN_getArg0Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN_getArg1Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN_getArg2Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN_getArg3Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
int glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN_getArg4Size(const GLuint *, const GLfloat *, const GLfloat *, const GLfloat *, const GLfloat *);
int glVertexWeightfvEXT_getArg0Size(const GLfloat *);
int glVertexWeightPointerEXT_getArg3Size(GLsizei, GLenum, GLsizei, const GLvoid *);
int glVertexArrayRangeNV_getArg1Size(GLsizei, const GLvoid *);
int glCombinerParameterfvNV_getArg1Size(GLenum, const GLfloat *);
int glCombinerParameterivNV_getArg1Size(GLenum, const GLint *);
int glMultiModeDrawArraysIBM_getArg0Size(const GLenum *, const GLint *, const GLsizei *, GLsizei, GLint);
int glMultiModeDrawArraysIBM_getArg1Size(const GLenum *, const GLint *, const GLsizei *, GLsizei, GLint);
int glMultiModeDrawArraysIBM_getArg2Size(const GLenum *, const GLint *, const GLsizei *, GLsizei, GLint);
int glMultiModeDrawElementsIBM_getArg0Size(const GLenum *, const GLsizei *, GLenum, const GLvoid* const *, GLsizei, GLint);
int glMultiModeDrawElementsIBM_getArg1Size(const GLenum *, const GLsizei *, GLenum, const GLvoid* const *, GLsizei, GLint);
int glMultiModeDrawElementsIBM_getArg3Size(const GLenum *, const GLsizei *, GLenum, const GLvoid* const *, GLsizei, GLint);
int glColorPointerListIBM_getArg3Size(GLint, GLenum, GLint, const GLvoid* *, GLint);
int glSecondaryColorPointerListIBM_getArg3Size(GLint, GLenum, GLint, const GLvoid* *, GLint);
int glEdgeFlagPointerListIBM_getArg1Size(GLint, const GLboolean* *, GLint);
int glFogCoordPointerListIBM_getArg2Size(GLenum, GLint, const GLvoid* *, GLint);
int glIndexPointerListIBM_getArg2Size(GLenum, GLint, const GLvoid* *, GLint);
int glNormalPointerListIBM_getArg2Size(GLenum, GLint, const GLvoid* *, GLint);
int glTexCoordPointerListIBM_getArg3Size(GLint, GLenum, GLint, const GLvoid* *, GLint);
int glVertexPointerListIBM_getArg3Size(GLint, GLenum, GLint, const GLvoid* *, GLint);
int glIglooInterfaceSGIX_getArg1Size(GLenum, const GLvoid *);
int glDeleteFencesNV_getArg1Size(GLsizei, const GLuint *);
int glMapControlPointsNV_getArg8Size(GLenum, GLuint, GLenum, GLsizei, GLsizei, GLint, GLint, GLboolean, const GLvoid *);
int glMapParameterivNV_getArg2Size(GLenum, GLenum, const GLint *);
int glMapParameterfvNV_getArg2Size(GLenum, GLenum, const GLfloat *);
int glCombinerStageParameterfvNV_getArg2Size(GLenum, GLenum, const GLfloat *);
int glDeleteProgramsNV_getArg1Size(GLsizei, const GLuint *);
int glExecuteProgramNV_getArg2Size(GLenum, GLuint, const GLfloat *);
int glLoadProgramNV_getArg3Size(GLenum, GLuint, GLsizei, const GLubyte *);
int glRequestResidentProgramsNV_getArg1Size(GLsizei, const GLuint *);
int glVertexAttribPointerNV_getArg4Size(GLuint, GLint, GLenum, GLsizei, const GLvoid *);
int glTexBumpParameterivATI_getArg1Size(GLenum, const GLint *);
int glTexBumpParameterfvATI_getArg1Size(GLenum, const GLfloat *);
int glSetFragmentShaderConstantATI_getArg1Size(GLuint, const GLfloat *);
int glNewObjectBufferATI_getArg1Size(GLsizei, const GLvoid *, GLenum);
int glUpdateObjectBufferATI_getArg3Size(GLuint, GLuint, GLsizei, const GLvoid *, GLenum);
int glSetInvariantEXT_getArg2Size(GLuint, GLenum, const GLvoid *);
int glSetLocalConstantEXT_getArg2Size(GLuint, GLenum, const GLvoid *);
int glVariantbvEXT_getArg1Size(GLuint, const GLbyte *);
int glVariantsvEXT_getArg1Size(GLuint, const GLshort *);
int glVariantivEXT_getArg1Size(GLuint, const GLint *);
int glVariantfvEXT_getArg1Size(GLuint, const GLfloat *);
int glVariantdvEXT_getArg1Size(GLuint, const GLdouble *);
int glVariantubvEXT_getArg1Size(GLuint, const GLubyte *);
int glVariantusvEXT_getArg1Size(GLuint, const GLushort *);
int glVariantuivEXT_getArg1Size(GLuint, const GLuint *);
int glVariantPointerEXT_getArg3Size(GLuint, GLenum, GLuint, const GLvoid *);
int glElementPointerATI_getArg1Size(GLenum, const GLvoid *);
int glDeleteOcclusionQueriesNV_getArg1Size(GLsizei, const GLuint *);
int glPointParameterivNV_getArg1Size(GLenum, const GLint *);
int glElementPointerAPPLE_getArg1Size(GLenum, const GLvoid *);
int glMultiDrawElementArrayAPPLE_getArg1Size(GLenum, const GLint *, const GLsizei *, GLsizei);
int glMultiDrawElementArrayAPPLE_getArg2Size(GLenum, const GLint *, const GLsizei *, GLsizei);
int glMultiDrawRangeElementArrayAPPLE_getArg3Size(GLenum, GLuint, GLuint, const GLint *, const GLsizei *, GLsizei);
int glMultiDrawRangeElementArrayAPPLE_getArg4Size(GLenum, GLuint, GLuint, const GLint *, const GLsizei *, GLsizei);
int glDeleteFencesAPPLE_getArg1Size(GLsizei, const GLuint *);
int glDeleteVertexArraysAPPLE_getArg1Size(GLsizei, const GLuint *);
int glVertexArrayRangeAPPLE_getArg1Size(GLsizei, GLvoid *);
int glFlushVertexArrayRangeAPPLE_getArg1Size(GLsizei, GLvoid *);
int glDrawBuffersATI_getArg1Size(GLsizei, const GLenum *);
int glProgramNamedParameter4fNV_getArg2Size(GLuint, GLsizei, const GLubyte *, GLfloat, GLfloat, GLfloat, GLfloat);
int glProgramNamedParameter4dNV_getArg2Size(GLuint, GLsizei, const GLubyte *, GLdouble, GLdouble, GLdouble, GLdouble);
int glFogCoordhvNV_getArg0Size(const GLhalfNV *);
int glVertexWeighthvNV_getArg0Size(const GLhalfNV *);
int glPixelDataRangeNV_getArg2Size(GLenum, GLsizei, GLvoid *);
int glDeleteRenderbuffersEXT_getArg1Size(GLsizei, const GLuint *);
int glDeleteFramebuffersEXT_getArg1Size(GLsizei, const GLuint *);
int glStringMarkerGREMEDY_getArg1Size(GLsizei, const GLvoid *);
int glVertexAttribIPointerEXT_getArg4Size(GLuint, GLint, GLenum, GLsizei, const GLvoid *);
int glBindFragDataLocationEXT_getArg2Size(GLuint, GLuint, const GLchar *);
int glDrawElementsInstancedEXT_getArg3Size(GLenum, GLsizei, GLenum, const GLvoid *, GLsizei);
int glProgramBufferParametersfvNV_getArg4Size(GLenum, GLuint, GLuint, GLsizei, const GLfloat *);
int glProgramBufferParametersIivNV_getArg4Size(GLenum, GLuint, GLuint, GLsizei, const GLint *);
int glProgramBufferParametersIuivNV_getArg4Size(GLenum, GLuint, GLuint, GLsizei, const GLuint *);
int glTransformFeedbackAttribsNV_getArg1Size(GLuint, const GLint *, GLenum);
int glTransformFeedbackVaryingsNV_getArg2Size(GLuint, GLsizei, const GLchar* *, GLenum);
int glActiveVaryingNV_getArg1Size(GLuint, const GLchar *);
int glTexParameterIivEXT_getArg2Size(GLenum, GLenum, const GLint *);
int glTexParameterIuivEXT_getArg2Size(GLenum, GLenum, const GLuint *);
/* NEW FUNCTIONS */
int glTransformFeedbackVaryingsEXT_getArg2Size(GLuint, GLsizei, const GLchar* *, GLenum);
int glMatrixLoadfEXT_getArg1Size(GLenum, const GLfloat *);
int glMatrixLoaddEXT_getArg1Size(GLenum, const GLdouble *);
int glMatrixMultfEXT_getArg1Size(GLenum, const GLfloat *);
int glMatrixMultdEXT_getArg1Size(GLenum, const GLdouble *);
int glMatrixLoadTransposefEXT_getArg1Size(GLenum, const GLfloat *);
int glMatrixLoadTransposedEXT_getArg1Size(GLenum, const GLdouble *);
int glMatrixMultTransposefEXT_getArg1Size(GLenum, const GLfloat *);
int glMatrixMultTransposedEXT_getArg1Size(GLenum, const GLdouble *);
int glTextureParameterfvEXT_getArg3Size(GLuint, GLenum, GLenum, const GLfloat *);
int glTextureParameterivEXT_getArg3Size(GLuint, GLenum, GLenum, const GLint *);
int glTextureImage1DEXT_getArg8Size(GLuint, GLenum, GLint, GLenum, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
int glTextureImage2DEXT_getArg9Size(GLuint, GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
int glTextureSubImage1DEXT_getArg7Size(GLuint, GLenum, GLint, GLint, GLsizei, GLenum, GLenum, const GLvoid *);
int glTextureSubImage2DEXT_getArg9Size(GLuint, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
int glTextureImage3DEXT_getArg10Size(GLuint, GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
int glTextureSubImage3DEXT_getArg11Size(GLuint, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
int glMultiTexParameterfvEXT_getArg3Size(GLenum, GLenum, GLenum, const GLfloat *);
int glMultiTexParameterivEXT_getArg3Size(GLenum, GLenum, GLenum, const GLint *);
int glMultiTexImage1DEXT_getArg8Size(GLenum, GLenum, GLint, GLenum, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
int glMultiTexImage2DEXT_getArg9Size(GLenum, GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
int glMultiTexSubImage1DEXT_getArg7Size(GLenum, GLenum, GLint, GLint, GLsizei, GLenum, GLenum, const GLvoid *);
int glMultiTexSubImage2DEXT_getArg9Size(GLenum, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
int glMultiTexImage3DEXT_getArg10Size(GLenum, GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid *);
int glMultiTexSubImage3DEXT_getArg11Size(GLenum, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *);
int glMultiTexCoordPointerEXT_getArg4Size(GLenum, GLint, GLenum, GLsizei, const GLvoid *);
int glMultiTexEnvfvEXT_getArg3Size(GLenum, GLenum, GLenum, const GLfloat *);
int glMultiTexEnvivEXT_getArg3Size(GLenum, GLenum, GLenum, const GLint *);
int glMultiTexGendvEXT_getArg3Size(GLenum, GLenum, GLenum, const GLdouble *);
int glMultiTexGenfvEXT_getArg3Size(GLenum, GLenum, GLenum, const GLfloat *);
int glMultiTexGenivEXT_getArg3Size(GLenum, GLenum, GLenum, const GLint *);
int glCompressedTextureImage3DEXT_getArg9Size(GLuint, GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *);
int glCompressedTextureImage2DEXT_getArg8Size(GLuint, GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *);
int glCompressedTextureImage1DEXT_getArg7Size(GLuint, GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, const GLvoid *);
int glCompressedTextureSubImage3DEXT_getArg11Size(GLuint, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *);
int glCompressedTextureSubImage2DEXT_getArg9Size(GLuint, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *);
int glCompressedTextureSubImage1DEXT_getArg7Size(GLuint, GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, const GLvoid *);
int glCompressedMultiTexImage3DEXT_getArg9Size(GLenum, GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *);
int glCompressedMultiTexImage2DEXT_getArg8Size(GLenum, GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, const GLvoid *);
int glCompressedMultiTexImage1DEXT_getArg7Size(GLenum, GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, const GLvoid *);
int glCompressedMultiTexSubImage3DEXT_getArg11Size(GLenum, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *);
int glCompressedMultiTexSubImage2DEXT_getArg9Size(GLenum, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, const GLvoid *);
int glCompressedMultiTexSubImage1DEXT_getArg7Size(GLenum, GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, const GLvoid *);
int glNamedProgramStringEXT_getArg4Size(GLuint, GLenum, GLenum, GLsizei, const GLvoid *);
int glTextureParameterIivEXT_getArg3Size(GLuint, GLenum, GLenum, const GLint *);
int glTextureParameterIuivEXT_getArg3Size(GLuint, GLenum, GLenum, const GLuint *);
int glMultiTexParameterIivEXT_getArg3Size(GLenum, GLenum, GLenum, const GLint *);
int glMultiTexParameterIuivEXT_getArg3Size(GLenum, GLenum, GLenum, const GLuint *);
int glProgramUniformMatrix2x3fvEXT_getArg4Size(GLuint, GLint, GLsizei, GLboolean, const GLfloat *);
int glProgramUniformMatrix3x2fvEXT_getArg4Size(GLuint, GLint, GLsizei, GLboolean, const GLfloat *);
int glProgramUniformMatrix2x4fvEXT_getArg4Size(GLuint, GLint, GLsizei, GLboolean, const GLfloat *);
int glProgramUniformMatrix4x2fvEXT_getArg4Size(GLuint, GLint, GLsizei, GLboolean, const GLfloat *);
int glProgramUniformMatrix3x4fvEXT_getArg4Size(GLuint, GLint, GLsizei, GLboolean, const GLfloat *);
int glProgramUniformMatrix4x3fvEXT_getArg4Size(GLuint, GLint, GLsizei, GLboolean, const GLfloat *);
int glNamedBufferDataEXT_getArg2Size(GLuint, GLsizeiptr, const GLvoid *, GLenum);
int glNamedBufferSubDataEXT_getArg3Size(GLuint, GLintptr, GLsizeiptr, const GLvoid *);
int glFramebufferDrawBuffersEXT_getArg2Size(GLuint, GLsizei, const GLenum *);
int glDeleteTransformFeedbacksNV_getArg1Size(GLsizei, const GLuint *);
int glDeletePerfMonitorsAMD_getArg1Size(GLsizei, GLuint *);
int glSelectPerfMonitorCountersAMD_getArg4Size(GLuint, GLboolean, GLuint, GLint, GLuint *);
int glTextureRangeAPPLE_getArg2Size(GLenum, GLsizei, const GLvoid *);
int glMapVertexAttrib1dAPPLE_getArg6Size(GLuint, GLuint, GLdouble, GLdouble, GLint, GLint, const GLdouble *);
int glMapVertexAttrib1fAPPLE_getArg6Size(GLuint, GLuint, GLfloat, GLfloat, GLint, GLint, const GLfloat *);
int glMapVertexAttrib2dAPPLE_getArg10Size(GLuint, GLuint, GLdouble, GLdouble, GLint, GLint, GLdouble, GLdouble, GLint, GLint, const GLdouble *);
int glMapVertexAttrib2fAPPLE_getArg10Size(GLuint, GLuint, GLfloat, GLfloat, GLint, GLint, GLfloat, GLfloat, GLint, GLint, const GLfloat *);
int glVideoCaptureNV_getArg1Size(GLuint, GLuint *, GLuint64EXT *);
int glVideoCaptureNV_getArg2Size(GLuint, GLuint *, GLuint64EXT *);
int glVideoCaptureStreamParameterivNV_getArg3Size(GLuint, GLuint, GLenum, const GLint *);
int glVideoCaptureStreamParameterfvNV_getArg3Size(GLuint, GLuint, GLenum, const GLfloat *);
int glVideoCaptureStreamParameterdvNV_getArg3Size(GLuint, GLuint, GLenum, const GLdouble *);
int glCreateShaderProgramEXT_getArg1Size(GLenum, const GLchar *);
int glUniformui64vNV_getArg2Size(GLint, GLsizei, const GLuint64EXT *);
int glProgramUniformui64vNV_getArg3Size(GLuint, GLint, GLsizei, const GLuint64EXT *);
/* NEW FUNCTIONS */

#endif

#endif
